---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dev-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: dev-app
    http:
      paths:
      - path: /
        backend:
          serviceName: dev-hello-world-java
          servicePort: nodeport
