---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    name: artifactory
    app: artifactory
spec:
  ports:
  - port: 32004
    name: artifactory
    targetPort: 8081
  selector:
    deployment: artifactory
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory-nodeport
  labels:
    app: artifactory
spec:
  ports:
    - port: 8081
      nodePort: 32004
      name: nodeport
  selector:
    deployment: artifactory
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-data-new
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: pfc
    deployment: artifactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfc
      deployment: artifactory
  template:
    metadata:
      labels:
        app: pfc
        deployment: artifactory
    spec:
      volumes:
        - name: artifactory-persistent-storage
          persistentVolumeClaim:
            claimName: artifactory-data-new
      containers:
      - name: artifactory
        image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
        ports:
          - containerPort: 8081
        volumeMounts:
          - mountPath: "/var/opt/jfrog/artifactory"
            name: artifactory-persistent-storage
